FROM python:3.11-slim

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      sshpass openssh-client rsync git build-essential && \
    pip install --no-cache-dir ansible ansible-core && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /ansible
# copy entrypoint that runs ansible-playbook (optional)
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
